### ISSUE TITLE
Missing check on URL added to provider configuration

### ISSUE THREAD

**Issue by kalkun** [camptocamp/terraform-provider-geoserver#36]
If the geoserver is not running at the url defined for the provider, it seems that the error message is very vague: `unsupported protocol scheme ""` Further, I'm not sure if there is any constructive way to get out of this state. It seems that its not possible to have the server itself be a resource without risking getting into this state - is that correct, or am I missing something?

**Comment by AlexGacon** [comment]
Hello. You probably right, there is no real check on the availability of a GS instance behind the URL. In my use, I generally works with a K8s cluster which injects the URL if and only if the instance is up and running so I didn't meet the case.

I will see how to improve that.
